version: 0.2

phases:
  install:
    commands:
      - aws configure set preview.cloudfront true
  build:
    commands:
      - git log --pretty=oneline -n 1
      - npm install -g yarn
      - yarn --version
      - npm --version
      - node --version
      - yarn install
      - yarn run-script ./scripts/codebuild.ts
artifacts:
  files:
    - '**/*'
